# Devices
GET http://localhost:3000/devices HTTP/1.1

###

POST http://localhost:3000/devices HTTP/1.1
content-type: application/json

{
   "color": "red",
   "partNumber": "090870",
   "category": "1"
}

###

GET http://localhost:3000/devices/3 HTTP/1.1

###
DELETE  http://localhost:3000/devices/3 HTTP/1.1

###

###----------------------------------------------------------------------------###

# Categories

GET http://localhost:3000/categories HTTP/1.1

###

POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "electronics"
}

###

GET http://localhost:3000/categories/1 HTTP/1.1

###

DELETE  http://localhost:3000/categories/3 HTTP/1.1