version: '3.7'

services:
  api:
    container_name: device-api
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
    entrypoint: npm run start:dev
    tty: true
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    networks:
      - device
    depends_on:
      - mysql

  mysql:
    container_name: db-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    tty: true
    networks:
      - device
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  device:
    driver: bridge
volumes:
  mysql-data:
